#define USART_TX_PORT gpioPortA
#define USART_TX_PIN 0
#define USART_TX_LOCATION USART_ROUTELOC0_TXLOC_LOC0 // 0
#define USART_RX_PORT gpioPortA
#define USART_RX_PIN 1
#define USART_RX_LOCATION USART_ROUTELOC0_RXLOC_LOC0 // 0
